# Generated by Django 4.0.4 on 2022-07-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_groups_account_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', max_length=200, null=True, upload_to='profile_images/%y/%m/%d', verbose_name='Profile Image'),
        ),
    ]
