# Generated by Django 4.0.4 on 2022-07-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hide_email',
            field=models.BooleanField(blank=True, default=True, verbose_name='Hide Email'),
        ),
    ]
